using System;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Net.Http;
using System.Windows;
using WAMP_DS.Views;
using WAMP_DS.Models;

namespace WAMP_DS.Managers
{
    public class WordPressManager
    {
        private const string WordPressDownloadUrl =
            "https://wordpress.org/latest.zip";

        private readonly DatabaseManager databaseManager;
        private readonly MySQLSettingsManager mySqlSettingsManager;
        private readonly string wpCliPath;
        private readonly string phpPath;

        public event EventHandler<string>? OutputReceived;

        public WordPressManager()
        {
            mySqlSettingsManager =
                new MySQLSettingsManager();

            databaseManager =
                new DatabaseManager(
                    mySqlSettingsManager
                );

            phpPath =
                Path.Combine(
                    AppContext.BaseDirectory,
                    "runtimes",
                    "php",
                    "8.5.8",
                    "php.exe"
                );

            wpCliPath =
                Path.Combine(
                    AppContext.BaseDirectory,
                    "tools",
                    "wp-cli",
                    "wp-cli.phar"
                );
        }

        public async Task<bool> CompleteInstallation(
            string projectPath,
            string databaseName,
            string virtualHostDomain,
            WordPressInstallSettings installSettings)
        {
            Report(
                "Creating WordPress database..."
            );

            await databaseManager.CreateDatabase(databaseName);

            Report(
                "WordPress database created."
            );

            await CreateWpConfig(
                projectPath,
                databaseName
            );

            bool installed =
                await RunWpCli(
                    $"core install " +
                    $"--url=\"https://{virtualHostDomain}\" " +
                    $"--title=\"{installSettings.SiteTitle}\" " +
                    $"--admin_user=\"{installSettings.AdminUsername}\" " +
                    $"--admin_password=\"{installSettings.AdminPassword}\" " +
                    $"--admin_email=\"{installSettings.AdminEmail}\"",
                    projectPath
                );

            if (!installed)
            {
                Report(
                    "WordPress installation failed."
                );

                return false;
            }

            Report(
                "WordPress installed successfully."
            );

            return true;
        }

        private async Task CreateWpConfig(
            string projectPath,
            string databaseName)
        {
            Report(
                "Creating wp-config.php..."
            );

            string configPath =
                Path.Combine(
                    projectPath,
                    "wp-config.php"
                );

            string template =
        $@"<?php
/**
 * WordPress Configuration
 * Generated by WAMP-DS
 */

define( 'DB_NAME', '{databaseName}' );
define( 'DB_USER', '{mySqlSettingsManager.Settings.Username}' );
define( 'DB_PASSWORD', '{mySqlSettingsManager.Settings.Password}' );
define( 'DB_HOST', '{mySqlSettingsManager.Settings.Host}' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

define( 'AUTH_KEY',         '{Guid.NewGuid()}' );
define( 'SECURE_AUTH_KEY',  '{Guid.NewGuid()}' );
define( 'LOGGED_IN_KEY',    '{Guid.NewGuid()}' );
define( 'NONCE_KEY',        '{Guid.NewGuid()}' );
define( 'AUTH_SALT',        '{Guid.NewGuid()}' );
define( 'SECURE_AUTH_SALT', '{Guid.NewGuid()}' );
define( 'LOGGED_IN_SALT',   '{Guid.NewGuid()}' );
define( 'NONCE_SALT',       '{Guid.NewGuid()}' );

$table_prefix = 'wp_';

if ( ! defined( 'ABSPATH' ) ) {{
    define( 'ABSPATH', __DIR__ . '/' );
}}

require_once ABSPATH . 'wp-settings.php';
";

            await File.WriteAllTextAsync(
                configPath,
                template
            );

            Report(
                "wp-config.php created."
            );
        }

        private async Task<bool> RunWpCli(
            string arguments,
            string workingDirectory)
        {
            Report(
                $"Running WP-CLI: {arguments}"
            );

            ProcessStartInfo startInfo =
                new ProcessStartInfo
                {
                    FileName = phpPath,
                    Arguments =
                        $"\"{wpCliPath}\" {arguments}",
                    WorkingDirectory = workingDirectory,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

            using Process process =
                new Process
                {
                    StartInfo = startInfo
                };

            process.Start();

            string output =
                await process.StandardOutput.ReadToEndAsync();

            string error =
                await process.StandardError.ReadToEndAsync();

            await process.WaitForExitAsync();

            if (!string.IsNullOrWhiteSpace(output))
            {
                Report(output);
            }

            if (!string.IsNullOrWhiteSpace(error))
            {
                Report(error);
            }

            return process.ExitCode == 0;
        }

        private void Report(string message)
        {
            OutputReceived?.Invoke(
                this,
                message
            );
        }

        public async Task<string?> InstallWordPress(
            string location,
            string projectName,
            WordPressInstallSettings installSettings)
        {
            Report(
                $"WordPress site: {installSettings.SiteTitle}"
            );

            string projectPath =
                Path.Combine(
                    location,
                    projectName
                );

            string zipPath =
                Path.Combine(
                    location,
                    $"{projectName}.zip"
                );

            string extractPath =
                Path.Combine(
                    location,
                    $"{projectName}_temp"
                );

            try
            {
                Report("Building WordPress project...");
                Report($"Project location: {projectPath}");

                if (Directory.Exists(projectPath))
                {
                    Report(
                        "ERROR: Project directory already exists."
                    );

                    return null;
                }

                using HttpClient client = new();

                Report(
                    "Downloading WordPress..."
                );

                byte[] data =
                    await client.GetByteArrayAsync(
                        WordPressDownloadUrl
                    );

                await File.WriteAllBytesAsync(
                    zipPath,
                    data
                );

                Report(
                    "Extracting WordPress files..."
                );

                await Task.Run(() =>
                {
                    ZipFile.ExtractToDirectory(
                        zipPath,
                        extractPath
                    );
                });

                string wordpressFolder =
                    Path.Combine(
                        extractPath,
                        "wordpress"
                    );

                if (!Directory.Exists(wordpressFolder))
                {
                    Report(
                        "ERROR: WordPress archive structure invalid."
                    );

                    return null;
                }

                Directory.Move(
                    wordpressFolder,
                    projectPath
                );

                Directory.Delete(
                    extractPath,
                    true
                );

                File.Delete(
                    zipPath
                );

                Report(
                    "WordPress project created successfully."
                );

                return projectPath;
            }
            catch (Exception ex)
            {
                Report(
                    $"ERROR: {ex.Message}"
                );

                try
                {
                    if (File.Exists(zipPath))
                        File.Delete(zipPath);

                    if (Directory.Exists(extractPath))
                        Directory.Delete(
                            extractPath,
                            true
                        );
                }
                catch
                {
                }

                return null;
            }
        }

        public Task<WordPressInstallSettings?> GetInstallationSettings()
        {
            WordPressSettingsWindow settingsWindow =
                new WordPressSettingsWindow
                {
                    Owner = Application.Current.MainWindow
                };

            if (settingsWindow.ShowDialog() != true)
            {
                Report(
                    "WordPress installation cancelled."
                );

                return Task.FromResult<WordPressInstallSettings?>(null);
            }

            return Task.FromResult<WordPressInstallSettings?>(
                settingsWindow.Settings
            );
        }
    }
}